spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

logging:
  level:
    hiyen.galmanhae.dataprocess: DEBUG
    org.hibernate.type.descriptor.sql:
      BasicBinder: TRACE
    org.springframework: DEBUG
    org.springframework.cloud.openfeign: DEBUG
